server:
  port: 8888

# 连接四大参数
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jianniao
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
     minimum-idle: 60000    #空闲超时时间
     maximum-pool-size: 30  #连接池最大连接数量
  transaction:
    rollback-on-commit-failure: false

# mybatis 别名扫描
mybatis:
  type-aliases-package: fun.jianjie.miniorder.domain
pagehelper:   #分页器配置
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql
# mapper.xml文件位置,如果没有映射文件，请注释掉
#mybatis.mapper-locations=classpath:mappers/*.xml

#配置通用分页器


wx-config: #自定义的属性和值
  img_url_prefix: http://localhost:8888/img
  wx_app_id: wx53ee16a091421f41
  wx_app_secret: fcea20047c797a01c2b63280f8492c77
  wx_login_url: https://api.weixin.qq.com/sns/jscode2session?
  token_salt: HHsTieBU377mJtKr
  token_expire: 7200




